"""empty message

Revision ID: 14bac00ed167
Revises: f6099f020008
Create Date: 2026-04-06 07:55:46.704538

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "14bac00ed167"
down_revision = "f6099f020008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "application_contact",
        "cpf",
        existing_type=postgresql.BYTEA(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "application_contact",
        "cpf",
        existing_type=sa.String(),
        type_=postgresql.BYTEA(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
