"""empty message

Revision ID: 26d1888f1361
Revises: 39c964e7d573
Create Date: 2026-04-12 20:03:45.110041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d1888f1361'
down_revision = '39c964e7d573'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('national_id', sa.String(), nullable=False),
    sa.Column('trading_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id')
    )
    op.add_column('biometric_validation', sa.Column('provider_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_biometric_validation_profile_ref'), table_name='biometric_validation')
    op.create_index(op.f('ix_biometric_validation_provider_id'), 'biometric_validation', ['provider_id'], unique=False)
    op.drop_column('biometric_validation', 'profile_ref')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biometric_validation', sa.Column('profile_ref', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_biometric_validation_provider_id'), table_name='biometric_validation')
    op.create_index(op.f('ix_biometric_validation_profile_ref'), 'biometric_validation', ['profile_ref'], unique=False)
    op.drop_column('biometric_validation', 'provider_id')
    op.drop_table('customer')
    # ### end Alembic commands ###
