"""empty message

Revision ID: 39c964e7d573
Revises: 5321ddaf4f61
Create Date: 2026-04-07 15:27:27.701256

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "39c964e7d573"
down_revision = "5321ddaf4f61"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "originator_seller",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("national_id", sa.String(), nullable=False),
        sa.Column("position", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="COMPLETED", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"], ["application.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("application_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("originator_seller")
    # ### end Alembic commands ###
