"""empty message

Revision ID: b6ad299df24e
Revises: 26d1888f1361
Create Date: 2026-04-13 09:34:04.034218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ad299df24e'
down_revision = '26d1888f1361'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_consent', sa.Column('term_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('application_consent_terms_id_fkey'), 'application_consent', type_='foreignkey')
    op.create_foreign_key(None, 'application_consent', 'terms', ['term_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('application_consent', 'terms_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_consent', sa.Column('terms_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'application_consent', type_='foreignkey')
    op.create_foreign_key(op.f('application_consent_terms_id_fkey'), 'application_consent', 'terms', ['terms_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('application_consent', 'term_id')
    # ### end Alembic commands ###
