"""empty message

Revision ID: f6099f020008
Revises: 8fb8555dac74
Create Date: 2026-04-06 07:04:33.948510

"""

import uuid

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f6099f020008"
down_revision = "8fb8555dac74"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "terms",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.execute(
        sa.text(
            "INSERT INTO terms (id, version, link, is_active, created_at) "
            "VALUES (:id, :version, :link, :is_active, TIMEZONE('utc', CURRENT_TIMESTAMP))"
        ).bindparams(
            id=str(uuid.uuid7()),
            version=1,
            link="https://www.pedidoprotegido.com.br/termos",
            is_active=True,
        )
    )
    op.create_table(
        "application_consent",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("terms_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(), server_default="PENDING", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"], ["application.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["terms_id"], ["terms.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "biometric_validation",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("profile_ref", sa.String(), nullable=False),
        sa.Column(
            "status", sa.String(), server_default="AWAIT_CONFIRMATION", nullable=False
        ),
        sa.Column(
            "validation_result", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"], ["application.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_biometric_validation_profile_ref"),
        "biometric_validation",
        ["profile_ref"],
        unique=False,
    )
    op.create_index(
        op.f("ix_biometric_validation_status"),
        "biometric_validation",
        ["status"],
        unique=False,
    )
    op.create_table(
        "pix_charge",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("pix_id", sa.String(), nullable=False),
        sa.Column("transaction_id", sa.String(), nullable=True),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(), server_default="BRL", nullable=False),
        sa.Column("qr_code_text", sa.String(), nullable=True),
        sa.Column("qr_code_uri", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"], ["application.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pix_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pix_charge")
    op.drop_index(
        op.f("ix_biometric_validation_status"), table_name="biometric_validation"
    )
    op.drop_index(
        op.f("ix_biometric_validation_profile_ref"), table_name="biometric_validation"
    )
    op.drop_table("biometric_validation")
    op.drop_table("application_consent")
    op.drop_table("terms")
    # ### end Alembic commands ###
