"""empty message

Revision ID: fa1a724eafc8
Revises: b6ad299df24e
Create Date: 2026-04-13 17:48:04.968348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1a724eafc8'
down_revision = 'b6ad299df24e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
